[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = accounts marketplace
test_discovery = accounts marketplace
python_classes = True
addopts =
    -v
    --cov=. --cov-report=html --cov-report=term

[coverage:run]
branch = True
source = accounts marketplace
omit =
    */migrations/*
    */tests/*
    */venv/*
    */__pycache__/*
    .dockerignore
    .git/
    .github/
