# Generated by Django 6.0.2 on 2026-02-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_company_name"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(blank=True, related_name="projects", to="accounts.skill"),
        ),
    ]
