# Generated by Django 6.0.2 on 2026-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
